import type { Metadata } from "next";
import './globalStyles/globals.scss';
import { Varela_Round } from 'next/font/google'
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import PopUp from "@/Components/ElementComponents/PopUp/PopUp";

export const metadata: Metadata = {
  title: "Oxsilla Creative House | Web development and media productions",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/favicon.png",
  },
};

const varela = Varela_Round({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-varela', // laver en CSS variabel
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={varela.variable}>
      <body>
        <header>
          <Header />
        </header>
        <main>
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
        <PopUp
          heading="hey stranger!"
          text="ask us anything and we'll get back to you asap"
          button={{
            text: "contact",
            href: "/contact"
          }}
        />
      </body>
    </html>
  );
}
